# Generated by Django 4.0.3 on 2024-02-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0004_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Blood_Group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
