# Generated by Django 4.0.3 on 2024-02-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0005_employee_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Blood_Group',
        ),
    ]
